In [1]:
# -*- coding: utf-8 -*-# -*- c 

#!/usr/bin/python
# -*- coding: utf-8 -*-

Rotininha pra calcular o qui2 da contigency table de tipos morfológicos e perfis de Ha.

In [11]:
#Importando as bibliotecas

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time
import datetime
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from scipy.stats import norm
import matplotlib.mlab as mlab
from scipy.stats import chi2_contingency

%matplotlib inline

In [3]:
def obtendo_dados(img,param):
    '''função para leitura do arquivo fits, criando um dataframe com os dados'''
    df = pd.DataFrame()
    nrows, ncols = img.shape
    xx, yy = np.meshgrid( *np.ogrid[:ncols, :nrows] )
    table = np.column_stack(( xx.flatten(), yy.flatten(), img.flatten() ))
    temp = pd.DataFrame(table, columns=['x','y',param])
    df = pd.concat([df,temp], axis=1)
    return(df)

In [4]:
df_ct = pd.read_csv('contigency_table.csv')

In [5]:
ct = df_ct.values
nij = df_nij.values

In [27]:
chi2_contingency(ct, correction=True,lambda_='pearson')

(25.667638581514176,
 0.0002567206096824824,
 6,
 array([[ 5.37931034,  6.57471264,  5.67816092,  8.36781609],
        [ 4.55172414,  5.56321839,  4.8045977 ,  7.08045977],
        [ 8.06896552,  9.86206897,  8.51724138, 12.55172414]]))

Logo, rejeitamos a hipótese nula de que as variáveis não estão correlacionadas!

In [20]:
obs = np.array([[237,3,10], [106,4,7],[24,32,11]])

In [21]:
obs

array([[237,   3,  10],
       [106,   4,   7],
       [ 24,  32,  11]])

In [23]:
chi2_contingency(obs,lambda_="log-likelihood")

(124.59127254186693,
 5.581137096779196e-26,
 4,
 array([[211.40552995,  22.46543779,  16.12903226],
        [ 98.93778802,  10.51382488,   7.5483871 ],
        [ 56.65668203,   6.02073733,   4.32258065]]))

In [30]:
print(df_ct)

    C   S  F   R
0  11  10  4   1
1   1   2  6  13
2   6  10  9  14


In [31]:
display(df_ct)

C   S  F   R
0  11  10  4   1
1   1   2  6  13
2   6  10  9  14